-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-produnto_package_version-ppv_package.json
-- Manually edited to add the USING clause, which is required to convert TEXT to INT.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE produnto_package_version
  ALTER ppv_package TYPE INT USING ppv_package::INT;
