-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE produnto_active_deployment (
  pad_wiki TEXT NOT NULL,
  pad_deployment INT NOT NULL,
  PRIMARY KEY(pad_wiki)
);


CREATE TABLE produnto_deployment (
  pd_id SERIAL NOT NULL,
  pd_target_wiki TEXT NOT NULL,
  pd_control_wiki TEXT NOT NULL,
  pd_control_rev_id INT NOT NULL,
  PRIMARY KEY(pd_id)
);

CREATE INDEX pd_target_wiki_id ON produnto_deployment (pd_target_wiki, pd_id);


CREATE TABLE produnto_deployment_data (
  pdd_id SERIAL NOT NULL,
  pdd_deployment INT NOT NULL,
  pdd_name TEXT NOT NULL,
  pdd_text TEXT NOT NULL,
  PRIMARY KEY(pdd_id)
);

CREATE UNIQUE INDEX pdd_deployment_name ON produnto_deployment_data (pdd_deployment, pdd_name);


CREATE TABLE produnto_package_deployment (
  ppd_deployment INT NOT NULL,
  ppd_package_version INT NOT NULL,
  PRIMARY KEY(
    ppd_deployment, ppd_package_version
  )
);

CREATE INDEX ppd_package_version ON produnto_package_deployment (ppd_package_version);


CREATE TABLE produnto_package_version (
  ppv_id SERIAL NOT NULL,
  ppv_package TEXT NOT NULL,
  ppv_version TEXT NOT NULL,
  ppv_state SMALLINT NOT NULL,
  ppv_error TEXT DEFAULT NULL,
  PRIMARY KEY(ppv_id)
);

CREATE UNIQUE INDEX ppv_package_version ON produnto_package_version (ppv_package, ppv_version);


CREATE TABLE produnto_package (
  pp_id SERIAL NOT NULL,
  pp_name TEXT NOT NULL,
  pp_url TEXT NOT NULL,
  PRIMARY KEY(pp_id)
);

CREATE UNIQUE INDEX pp_name ON produnto_package (pp_name);


CREATE TABLE produnto_file (
  pf_id SERIAL NOT NULL,
  pf_package_version INT NOT NULL,
  pf_name_id INT NOT NULL,
  pf_hash TEXT NOT NULL,
  PRIMARY KEY(pf_id)
);

CREATE INDEX produnto_file_package_name ON produnto_file (pf_package_version, pf_name_id);

CREATE INDEX produnto_file_name_package ON produnto_file (pf_name_id, pf_package_version);

CREATE INDEX pf_hash ON produnto_file (pf_hash);


CREATE TABLE produnto_file_name (
  pfn_id SERIAL NOT NULL,
  pfn_name TEXT NOT NULL,
  PRIMARY KEY(pfn_id)
);

CREATE UNIQUE INDEX pfn_name ON produnto_file_name (pfn_name);


CREATE TABLE produnto_file_text (
  pft_hash TEXT NOT NULL,
  pft_text TEXT NOT NULL,
  PRIMARY KEY(pft_hash)
);
