-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-produnto_package_version-ppv_package.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__produnto_package_version AS
SELECT
  ppv_id,
  ppv_package,
  ppv_version,
  ppv_upstream_ref,
  ppv_state,
  ppv_error,
  ppv_props
FROM /*_*/produnto_package_version;

DROP TABLE /*_*/produnto_package_version;


CREATE TABLE /*_*/produnto_package_version (
  ppv_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ppv_package INTEGER UNSIGNED NOT NULL,
  ppv_version BLOB NOT NULL, ppv_upstream_ref BLOB NOT NULL,
  ppv_state SMALLINT NOT NULL, ppv_error BLOB DEFAULT NULL,
  ppv_props BLOB NOT NULL
);

INSERT INTO /*_*/produnto_package_version (
  ppv_id, ppv_package, ppv_version,
  ppv_upstream_ref, ppv_state, ppv_error,
  ppv_props
)
SELECT
  ppv_id,
  ppv_package,
  ppv_version,
  ppv_upstream_ref,
  ppv_state,
  ppv_error,
  ppv_props
FROM /*_*/__temp__produnto_package_version;

DROP TABLE /*_*/__temp__produnto_package_version;

CREATE UNIQUE INDEX ppv_package_version ON /*_*/produnto_package_version (ppv_package, ppv_version);
