-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/produnto_active_deployment (
  pad_wiki BLOB NOT NULL,
  pad_deployment INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(pad_wiki)
);


CREATE TABLE /*_*/produnto_deployment (
  pd_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pd_target_wiki BLOB NOT NULL, pd_control_wiki BLOB NOT NULL,
  pd_control_rev_id INTEGER UNSIGNED NOT NULL
);

CREATE INDEX pd_target_wiki_id ON /*_*/produnto_deployment (pd_target_wiki, pd_id);


CREATE TABLE /*_*/produnto_deployment_data (
  pdd_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pdd_deployment INTEGER UNSIGNED NOT NULL,
  pdd_name BLOB NOT NULL, pdd_text BLOB NOT NULL
);

CREATE UNIQUE INDEX pdd_deployment_name ON /*_*/produnto_deployment_data (pdd_deployment, pdd_name);


CREATE TABLE /*_*/produnto_package_deployment (
  ppd_deployment INTEGER UNSIGNED NOT NULL,
  ppd_package_version INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(
    ppd_deployment, ppd_package_version
  )
);

CREATE INDEX ppd_package_version ON /*_*/produnto_package_deployment (ppd_package_version);


CREATE TABLE /*_*/produnto_package_version (
  ppv_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ppv_package BLOB NOT NULL, ppv_version BLOB NOT NULL,
  ppv_state SMALLINT NOT NULL, ppv_error BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX ppv_package_version ON /*_*/produnto_package_version (ppv_package, ppv_version);


CREATE TABLE /*_*/produnto_package (
  pp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pp_name BLOB NOT NULL, pp_url BLOB NOT NULL
);

CREATE UNIQUE INDEX pp_name ON /*_*/produnto_package (pp_name);


CREATE TABLE /*_*/produnto_file (
  pf_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pf_package_version INTEGER UNSIGNED NOT NULL,
  pf_name_id INTEGER UNSIGNED NOT NULL,
  pf_hash BLOB NOT NULL
);

CREATE INDEX produnto_file_package_name ON /*_*/produnto_file (pf_package_version, pf_name_id);

CREATE INDEX produnto_file_name_package ON /*_*/produnto_file (pf_name_id, pf_package_version);

CREATE INDEX pf_hash ON /*_*/produnto_file (pf_hash);


CREATE TABLE /*_*/produnto_file_name (
  pfn_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pfn_name BLOB NOT NULL
);

CREATE UNIQUE INDEX pfn_name ON /*_*/produnto_file_name (pfn_name);


CREATE TABLE /*_*/produnto_file_text (
  pft_hash BLOB NOT NULL,
  pft_text BLOB NOT NULL,
  PRIMARY KEY(pft_hash)
);
