-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-produnto_file_name-pfn_name.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/produnto_file_name
  CHANGE pfn_name pfn_name VARBINARY(3072) NOT NULL;
