-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-produnto_package_version-ppv_package.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/produnto_package_version
  CHANGE ppv_package ppv_package INT UNSIGNED NOT NULL;
