-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/produnto_active_deployment (
  pad_wiki VARBINARY(255) NOT NULL,
  pad_deployment INT UNSIGNED NOT NULL,
  PRIMARY KEY(pad_wiki)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_deployment (
  pd_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pd_target_wiki VARBINARY(255) NOT NULL,
  pd_control_wiki VARBINARY(255) NOT NULL,
  pd_control_rev_id INT UNSIGNED NOT NULL,
  INDEX pd_target_wiki_id (pd_target_wiki, pd_id),
  PRIMARY KEY(pd_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_deployment_data (
  pdd_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pdd_deployment INT UNSIGNED NOT NULL,
  pdd_name VARBINARY(255) NOT NULL,
  pdd_text LONGBLOB NOT NULL,
  UNIQUE INDEX pdd_deployment_name (pdd_deployment, pdd_name),
  PRIMARY KEY(pdd_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_package_deployment (
  ppd_deployment INT UNSIGNED NOT NULL,
  ppd_package_version INT UNSIGNED NOT NULL,
  INDEX ppd_package_version (ppd_package_version),
  PRIMARY KEY(
    ppd_deployment, ppd_package_version
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_package_version (
  ppv_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ppv_package VARBINARY(255) NOT NULL,
  ppv_version VARBINARY(255) NOT NULL,
  ppv_upstream_ref VARBINARY(255) NOT NULL,
  ppv_state TINYINT(1) NOT NULL,
  ppv_error BLOB DEFAULT NULL,
  ppv_props MEDIUMBLOB NOT NULL,
  UNIQUE INDEX ppv_package_version (ppv_package, ppv_version),
  PRIMARY KEY(ppv_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_package (
  pp_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pp_name VARBINARY(255) NOT NULL,
  pp_url BLOB NOT NULL,
  UNIQUE INDEX pp_name (pp_name),
  PRIMARY KEY(pp_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_file (
  pf_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pf_package_version INT UNSIGNED NOT NULL,
  pf_name_id INT UNSIGNED NOT NULL,
  pf_hash BINARY(64) NOT NULL,
  INDEX produnto_file_package_name (pf_package_version, pf_name_id),
  INDEX produnto_file_name_package (pf_name_id, pf_package_version),
  INDEX pf_hash (pf_hash),
  PRIMARY KEY(pf_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_file_name (
  pfn_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pfn_name VARBINARY(4095) NOT NULL,
  UNIQUE INDEX pfn_name (pfn_name),
  PRIMARY KEY(pfn_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/produnto_file_text (
  pft_hash BINARY(64) NOT NULL,
  pft_text LONGBLOB NOT NULL,
  PRIMARY KEY(pft_hash)
) /*$wgDBTableOptions*/;
